questions =  [
    {"id": 0, "question": "A liberdade de fazer negócios é a melhor forma da sociedade prosperar.", "effects": {"right": 1}},
    {"id": 1, "question": "A caridade privada é uma forma melhor de ajudar os mais pobres do que os apoios do Estado.", "effects": {"right": 1}},
    {"id": 2, "question": "Os salários são sempre justos porque os patrões sabem melhor quanto vale o trabalho de cada funcionário. ", "effects": {"right": 1}},
    {"id": 3, "question": "É da \"natureza humana\" ser ganancioso.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Exploração\" é uma palavra desatualizada, porque as lutas contra o capitalismo já não existem.", "effects": {"right": 1}},
    {"id": 5, "question": "O Comunismo é um ideal que nunca funcionaria na prática.", "effects": {"right": 1}},
    {"id": 6, "question": "Cobrar impostos aos mais ricos é uma má ideia, a sociedade estaria melhor sem isso.", "effects": {"right": 1}},
    {"id": 7, "question": "Quanto mais trabalhares, mais progrides na vida.", "effects": {"right": 1}},
    {"id": 8, "question": "As empresas não são de confiança e devem ser reguladas pelo Estado.", "effects": {"right": -1}},
    {"id": 9, "question": "Haver um governo que cuida de todos é uma boa ideia.", "effects": {"right": -1}},
    {"id": 10, "question": "O atual sistema de segurança social deveria ser alargado para melhor combater as desigualdades.", "effects": {"right": -1}},
    {"id": 11, "question": "Os terrenos não deveriam ser mercadoria para compra e venda.", "effects": {"right": -1}},
    {"id": 12, "question": "Todas as indústrias e bancos devem ser nacionalizados (ou seja, ficar na posse do Estado).", "effects": {"right": -1}},
    {"id": 13, "question": "A principal divisão da sociedade são as classes sociais.", "effects": {"right": -1}},
    {"id": 14, "question": "Há demasiada desigualdade económica no mundo. ", "effects": {"right": -1}},
    {"id": 15, "question": "Por vezes é correto que o governo vigie os seus cidadãos para combater extremismos e terrorismos.", "effects": {"auth": 1}},
    {"id": 16, "question": "As autoridades, desde que cumpram as normas morais, são algo bom para a sociedade.", "effects": {"auth": 1}},
    {"id": 17, "question": "O exercício da força pelo Estado é necessário para o sucesso da governação.", "effects": {"auth": 1}},
    {"id": 18, "question": "Apenas o governo pode, de forma justa e efetiva, regular as empresas e outras organizações", "effects": {"auth": 1}},
    {"id": 19, "question": "A sociedade precisa de uma estrutura e regras para funcionar.", "effects": {"auth": 1}},
    {"id": 20, "question": "O cartão de cidadão obrigatório é algo importante para a segurança pública.", "effects": {"auth": 1}},
    {"id": 21, "question": "Em tempos de crise, a segurança é mais importante do que a liberdade.", "effects": {"auth": 1}},
    {"id": 22, "question": "Se não tens nada a esconder, então não tens nada a temer.", "effects": {"auth": 1}},
    {"id": 23, "question": "O governo devia envolver-se menos na vida dos cidadãos.", "effects": {"auth": -1}},
    {"id": 24, "question": "Sem democracia, a sociedade não é nada.", "effects": {"auth": -1}},
    {"id": 25, "question": "A absolvição de um réu por um júri, mesmo contra a opinião do juiz, deve ser permitida.", "effects": {"auth": -1}},
    {"id": 26, "question": "Quanto menor o governo, mais livres são as pessoas.", "effects": {"auth": -1}},
    {"id": 27, "question": "O governo não deveria fornecer mais do que os serviços de urgência e a aplicação da lei.", "effects": {"auth": -1}},
    {"id": 28, "question": "A polícia não foi criada para proteger o povo, mas sim para manter o Estado e o sistema à força.", "effects": {"auth": -1}},
    {"id": 29, "question": "Escolas Públicas são uma má ideia porque o Estado não deveria influenciar as crianças.", "effects": {"auth": -1}},
    {"id": 30, "question": "Dois adultos numa relação consentida devem poder fazer o que quiserem, mesmo que isso me deixe desconfortável.", "effects": {"prog": 1}},
    {"id": 31, "question": "Cada pessoa é dona do seu corpo e deve poder fazer o que quiser com ele.", "effects": {"prog": 1}},
    {"id": 32, "question": "Uma pessoa deve poder seguir o culto religioso que quiser.", "effects": {"prog": 1}},
    {"id": 33, "question": "Nudismo é perfeitamente natural.", "effects": {"prog": 1}},
    {"id": 34, "question": "Os animais devem ter alguns direitos universais.", "effects": {"prog": 1}},
    {"id": 35, "question": "O género é uma construção social, não um estado natural das coisas.", "effects": {"prog": 1}},
    {"id": 36, "question": "Leis baseadas em valores culturais, em vez de valores éticos, não são justiça.", "effects": {"prog": 1}},
    {"id": 37, "question": "O direito à autonomia do próprio corpo deve aplicar-se também aos menores, aos doentes mentais e aos criminosos.", "effects": {"prog": 1}},
    {"id": 38, "question": "A homossexualidade é contra os meus valores.", "effects": {"prog": -1}},
    {"id": 39, "question": "Os indivíduos transgénero não deveriam poder adotar crianças.", "effects": {"prog": -1}},
    {"id": 40, "question": "As drogas são perigosas e devem ser banidas.", "effects": {"prog": -1}},
    {"id": 41, "question": "Devia haver pena de morte para certos crimes.", "effects": {"prog": -1}},
    {"id": 42, "question": "Crimes sem vítimas deveriam ser punidos na mesma.", "effects": {"prog": -1}},
    {"id": 43, "question": "Não é possível ter moral sem ter religião.", "effects": {"prog": -1}},
    {"id": 44, "question": "Os pais deviam de ter controlo absoluto nos filhos, pois são mais velhos e mais experientes.", "effects": {"prog": -1}},
    {"id": 45, "question": "O multiculturalismo é mau.", "effects": {"prog": -1}}
];
