questions =  [
    {"id": 0, "question": "A liberdade de negócios é a melhor forma da sociedade prosperar.", "effects": {"right": 1}},
    {"id": 1, "question": "A caridade privada é uma forma melhor de ajudar os mais pobres do que o aparelho do Estado", "effects": {"right": 1}},
    {"id": 2, "question": "Os salários são sempre justos porque os patrões sabem sempre o que é melhor para o trabalhador.", "effects": {"right": 1}},
    {"id": 3, "question": "É da \"natureza humana\" ser ganancioso.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Exploração\" é uma palavra desatualizada, porque as lutas contra o capitalismo já não existem.", "effects": {"right": 1}},
    {"id": 5, "question": "O Comunismo é um ideal que nunca funcionaria na prática.", "effects": {"right": 1}},
    {"id": 6, "question": "Cobrar impostos aos mais ricos é uma má ideia, a sociedade estaria melhor sem isso.", "effects": {"right": 1}},
    {"id": 7, "question": "Quanto mais trabalhares, mais progrides na vida.", "effects": {"right": 1}},
    {"id": 8, "question": "As empresas não podem ser confiadas e precisam de ser controladas pelo Estado.", "effects": {"right": -1}},
    {"id": 9, "question": "Um governo que dê a todos é uma ideia boa.", "effects": {"right": -1}},
    {"id": 10, "question": "O atual sistema de segurança social deve ser aumentado de forma a ajudar os mais pobres.", "effects": {"right": -1}},
    {"id": 11, "question": "Os terrenos não devem ser algo para vender e comprar.", "effects": {"right": -1}},
    {"id": 12, "question": "Todas as indústrias e bancos devem ser nacionalizados (ou seja, ficar na posse do Estado).", "effects": {"right": -1}},
    {"id": 13, "question": "O principal divisor da sociedade são as Classes.", "effects": {"right": -1}},
    {"id": 14, "question": "A desigualdade económica é muito alta no mundo.", "effects": {"right": -1}},
    {"id": 15, "question": "Por vezes é correto que o governo espie os seus cidadãos para combater extremismos e terrorismos.", "effects": {"auth": 1}},
    {"id": 16, "question": "Ditadores, se moralmente corretos, são algo bom para a sociedade.", "effects": {"auth": 1}},
    {"id": 17, "question": "A força (no sentido autoritário do Estado) é algo bom para qualquer governo ter sucesso.", "effects": {"auth": 1}},
    {"id": 18, "question": "Apenas o governo pode, de forma justa, regular as empresas.", "effects": {"auth": 1}},
    {"id": 19, "question": "A sociedade precisa de uma estrutura e regras para funcionar.", "effects": {"auth": 1}},
    {"id": 20, "question": "O cartão de cidadão obrigatório é algo importante para a segurança pública.", "effects": {"auth": 1}},
    {"id": 21, "question": "Em tempos de crise, a segurança vem primeiro do que a liberdade.", "effects": {"auth": 1}},
    {"id": 22, "question": "Se não tens nada a esconder, então não tens que temer nada.", "effects": {"auth": 1}},
    {"id": 23, "question": "O governo devia de estar menos envolvido na vida dos cidadãos.", "effects": {"auth": -1}},
    {"id": 24, "question": "Sem democracia, a sociedade não é nada.", "effects": {"auth": -1}},
    {"id": 25, "question": "A nulificação por júri (ou seja, os jurados votarem pela inocência de um réu independentemente da lei) deve ser legal.", "effects": {"auth": -1}},
    {"id": 26, "question": "Quanto menor o governo, mais livres são as pessoas.", "effects": {"auth": -1}},
    {"id": 27, "question": "O governo deve, pelo menos, fornecer serviços de emergência e de aplicação da lei.", "effects": {"auth": -1}},
    {"id": 28, "question": "A polícia não foi criada para proteger o povo, mas sim para manter o Estado e o sistema à força.", "effects": {"auth": -1}},
    {"id": 29, "question": "Escolas Públicas são uma má ideia porque o Estado não deveria influenciar as crianças.", "effects": {"auth": -1}},
    {"id": 30, "question": "Duas pessoas consentidas devem fazer o que quer que quiserem uma com a outra, mesmo se isso me deixa desconfortável.", "effects": {"prog": 1}},
    {"id": 31, "question": "O corpo de uma pessoa é a sua propriedade, e deve fazer o que quiser com ele.", "effects": {"prog": 1}},
    {"id": 32, "question": "Uma pessoa deve ser capaz de amar quem ou o que quiser.", "effects": {"prog": 1}},
    {"id": 33, "question": "Nudismo é perfeitamente natural.", "effects": {"prog": 1}},
    {"id": 34, "question": "Os animais merecem um certo tipo de direito universal.", "effects": {"prog": 1}},
    {"id": 35, "question": "O género é uma construção social, não um estado natural das coisas.", "effects": {"prog": 1}},
    {"id": 36, "question": "Leis baseadas em valores culturais, em vez de valores éticos, não são justiça.", "effects": {"prog": 1}},
    {"id": 37, "question": "A autonomia do corpo extende-se aos menores de idade, doentes mentais, e criminosos.", "effects": {"prog": 1}},
    {"id": 38, "question": "A homossexualidade é contra os meus valores.", "effects": {"prog": -1}},
    {"id": 39, "question": "Os indivíduos transgénero não deveriam adotar crianças.", "effects": {"prog": -1}},
    {"id": 40, "question": "As drogas são perigosas e devem ser banidas.", "effects": {"prog": -1}},
    {"id": 41, "question": "A pena de morte deveria existir em certos casos.", "effects": {"prog": -1}},
    {"id": 42, "question": "Crimes sem vítimas deveriam ser punidos na mesma.", "effects": {"prog": -1}},
    {"id": 43, "question": "Uma pessoa não pode ser moral sem a religião.", "effects": {"prog": -1}},
    {"id": 44, "question": "Os pais deviam de ter controlo absoluto nos filhos, pois são mais velhos e mais experientes.", "effects": {"prog": -1}},
    {"id": 45, "question": "O multiculturalismo é mau.", "effects": {"prog": -1}}
];
